### PR TITLE
Fixes for native image

### LINKED ISSUE #157: Including this module fails the native image build
### Expected Behavior

Native image build works.

### Actual Behaviour

```
Error: Classes that should be initialized at run time got initialized during image building:
 org.codehaus.stax2.typed.Base64Variants was unintentionally initialized at build time. com.fasterxml.jackson.dataformat.xml.util.StaxUtil$Base64Mapper caused initialization of this class with the following trace: 
        at org.codehaus.stax2.typed.Base64Variants.<clinit>(Base64Variants.java:36)
        at com.fasterxml.jackson.dataformat.xml.util.StaxUtil$Base64Mapper.<init>(StaxUtil.java:144)
        at com.fasterxml.jackson.dataformat.xml.util.StaxUtil$Base64Mapper.<clinit>(StaxUtil.java:139)
```

### Steps To Reproduce

Just include this module in `build.gradle`.

### Environment Information

_No response_

### Example Application

_No response_

### Version

3.2.4

### LINKED ISSUE #183: Using micronaut-jackson-xml gives error when building native image
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new protect like ```mn create-app me.jics.main --build maven  -f openapi,lombok,graalvm,security-jwt```
2. Add micronaut-jackson-xml as dependency in the ```pom.xml```
3. Add other configs for the native builder
4. Run ```./mvnw package -Dpackaging=native-image```

### Expected Behaviour

The build must be successful

### Actual Behaviour

The build shows an error

### Environment Information

- **Operating System**: Arch Linux
- **Micronaut Version:** 2.4.1
- **JDK Version:**
      
       $ native-image --version
       GraalVM Version 21.0.0.2 (Java Version 11.0.10+8-jvmci-21.0-b06)

       $ java -version
       openjdk version "11.0.10" 2021-01-19
       OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
       OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

### Example Application

- https://github.com/j1cs/micronaut-jacksonxml-error

###  Stacktrace
```
[INFO] Executing: /opt/graalvm-ce-java11-21.0.0/lib/svm/bin/native-image -cp ...
root/.m2/repository/org/codehaus/woodstox/stax2-api/4.2.1/stax2-api-4.2.1.jar:/root/.m2/repository/com/fasterxml/woodstox/woodstox-core/6.2.4/woodstox-core-6.2.4.jar --no-fallback -cp /home/app/target/main-1.0.jar -J-Dfile.encoding=UTF-8 -H:Class=me.jics.Application -H:Name=main
[main:127]    classlist:   5,282.69 ms,  0.94 GB
[main:127]        (cap):   1,071.42 ms,  0.94 GB
[main:127]        setup:   3,531.15 ms,  0.94 GB
Warning: class initialization of class io.micronaut.validation.exceptions.ValidationExceptionHandler failed with exception java.lang.NoClassDefFoundError: org/grails/datastore/mapping/validation/ValidationException. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.micronaut.validation.exceptions.ValidationExceptionHandler to explicitly request delayed initialization of this class.
To see how the classes got initialized, use --trace-class-initialization=org.codehaus.stax2.typed.Base64Variants
[main:127]     analysis:  57,488.71 ms,  2.10 GB
Error: Classes that should be initialized at run time got initialized during image building:
 org.codehaus.stax2.typed.Base64Variants was unintentionally initialized at build time. To see why org.codehaus.stax2.typed.Base64Variants got initialized use --trace-class-initialization=org.codehaus.stax2.typed.Base64Variants

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

### PR DESCRIPTION
**Pull request by altro3**
Found some problems when use graalvm with jackson-xml.

Fixed #157
Fixed #183

### CODE REVIEW

**Comment by altro3** [comment]
@sdelamo Hi! Found some problems with graalvm. This PR fix them

**Comment by sdelamo** [comment]
@altro3  could you add a test? https://github.com/micronaut-projects/micronaut-security/tree/master/test-suite-graal

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
@altro3 GraalVM tests fail.

``` 
$ sdk use java 22.3.r17-grl
$ ./gradlew testNative
```

**Comment by altro3** [comment]
@sdelamo fixed

**Comment by altro3** [comment]
@sdelamo Hm... Very strange error:
```
io.micronaut.http.codec.CodecException: Error encoding object [io.micronaut.xml.jackson.graal.Book@34cd08f3] to JSON: Failed to find class `com.fasterxml.jackson.databind.ext.CoreXMLSerializers` for handling values of type `com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl`, problem: (java.lang.ClassNotFoundException) com.fasterxml.jackson.databind.ext.CoreXMLSerializers (through reference chain: io.micronaut.xml.jackson.graal.Book["date"])
```
Look to my changes:
изображение
This settings must solve this problem, but I think that these settings were not applied in the test, because with the same settings my application works correctly in my project. Or did I do something wrong? Perhaps I should have specified other directories to include these settings. Could you help?

**Comment by altro3** [comment]
@sdelamo What about this? Could you help with this test?

**Comment by sdelamo** [comment]
@msupic is this something you could help with?

**Comment by msupic** [comment]
@sdelamo - I modified metadata files in the `jackson-xml` module to contain only metadata required by the `test-suite-graal` test. If some additional metadata are needed, the test need to be modified. Also did some minor refactoring in the test module (moved a few files from the `test` to the `main` directory) so resource files (`application.yml`, `logback.xml` etc.) get auto detected by the Native Build Tool plugin and added to auto generated `resource-config.json` file

**Comment by altro3** [comment]
@msupic I think you missed this arguments: `--initialize-at-run-time=com.fasterxml.jackson.dataformat.xml.util.StaxUtil$Base64Mapper --initialize-at-build-time=com.fasterxml.jackson.core.Base64Variants`

**Comment by altro3** [comment]
@msupic By the way. one of the cases is described in the issue https://github.com/micronaut-projects/micronaut-jackson-xml/issues/157 - look at the class name

**Comment by msupic** [comment]
The case from https://github.com/micronaut-projects/micronaut-jackson-xml/issues/157 is covered with current settings:
`Args = --initialize-at-build-time=org.codehaus.stax2.typed.Base64Variants`. There is no need to add `com.fasterxml.jackson.dataformat.xml.util.StaxUtil$Base64Mapper` because entire package `com.fasterxml.jackson` is set to build time in the `native-image.properties` file in the `micronaut-jackson-core` module (because of that we need `org.codehaus.stax2.typed.Base64Variants` also set to build time, which has been removed in Micronaut 4). Also I think we should not add metadata that we can't cover with tests since GraalVM native implementation is changing over time and some metadata that were required in that past or not required anymore and because of that it is important everything to be covered with tests. If somebody has an issue with existing metadata, we can easily add more if they can provide valid test case. Also, we are removing all third party metadata from Micronaut 4 since those will be stored in the shared metadata repository: https://github.com/oracle/graalvm-reachability-metadata

**Comment by altro3** [comment]
Well, well then, so be it. Since I'm already working on the next project where I no longer need this module, I won't be able to provide you with cases where I got errors related to these classes. So fix, please, at least these 2 issues.

In any case, these are not critical problems, and you can always add the necessary configurations yourself in your project

**Comment by msupic** [comment]
@sdelamo - please review

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
